version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet
  web1:
    build:
      context: ./src
    environment:
      PYTHONPATH: /app/src
      SERVER_ID: SERVER-1
      RUN_MIGRATIONS: "true" # web1 создаст таблицы
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet
      

  web2:
    build:
      context: ./src
    environment:
      PYTHONPATH: /app/src
      SERVER_ID: SERVER-2
      RUN_MIGRATIONS: "false"  # web2 не будет пытаться создавать таблицы
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
  
