name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
 
      - name: Set up Docker Compose
        run: docker-compose version

      - name: Build and Start Docker Containers
        run: docker-compose up -d --build

      

      - name: Wait for Services to Start
        run: sleep 10 # Даем контейнерам время запуститься

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install flake8 pytest
          pip install httpx

      - name: Run Flake8 (Static Analysis)
        run: flake8 src --max-line-length=88
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Debug List files
        run: ls -R
      
      - name: Проверка работающих контейнеров
        run: docker ps -a

      - name: Run Unit Tests
        run: pytest tests/test_unit.py

      - name: Run Integration Tests
        run: pytest tests/test_integration.py
      
      - name: Stop Docker Containers
        run: docker-compose down
